### ISSUE TITLE
Memory Block Game

### ISSUE THREAD

**Issue by RahulScripted** [Evgenii-Bazhaov/Hacktoberfest2024#12]
I want to add a memory block game using HTML,CSS,JS

![Screenshot 2024-10-13 100555](https://github.com/user-attachments/assets/a84d4479-02ae-429b-a150-7edcd26b106a)

**Comment by 2021eo3ar** [comment]
@RahulScripted could you please assign me this issue.

**Comment by Evgenii-Bazhaov** [comment]
nice work!
@RahulScripted Add the required files

**Comment by RahulScripted** [comment]
> nice work! @RahulScripted Add the required files

Added Thank you...😊
