### ISSUE TITLE
Hey I can make a tic-tac-toe game, could you please assign me this issue with hacktober fest label.

### ISSUE THREAD

**Issue by 2021eo3ar** [Evgenii-Bazhaov/Hacktoberfest2024#13]

**Comment by Evgenii-Bazhaov** [comment]
@2021eo3ar yes you can add

**Comment by 2021eo3ar** [comment]
Hey @Evgenii-Bazhaov I have Raised a new PR  for tic-tac-toe game made using React.js and tailwind css, to run the game you need to first navigate to tic-tac-toe folder, then right click on it and select `open with integrated terminal`  option, And after opening it run this command `npm i` and then `npm run dev`. here is the screen shot of the game :- 
![Screenshot 2024-10-13 203951](https://github.com/user-attachments/assets/ab478670-d74d-4957-9582-6d68b3042c5a)
