### ISSUE TITLE
Eyes Follow Cursor

### ISSUE THREAD

**Issue by RahulScripted** [Evgenii-Bazhaov/Hacktoberfest2024#15]
I want to add a new project that is eyes that follow cursor using HTML, CSS & JS. Here is the preview-

![Screenshot 2024-10-13 201630](https://github.com/user-attachments/assets/5c55d075-b73e-45a9-b7a2-80a0ab3d7b86)

**Comment by Evgenii-Bazhaov** [comment]
@RahulScripted  yes you can add

**Comment by RahulScripted** [comment]
> @RahulScripted Yes you can add

@Evgenii-Bazhaov Could you also attach the gssoc-ext label as it will help me to contribute to Girlscript summer of code

**Comment by Evgenii-Bazhaov** [comment]
Hey 👋,  @RahulScripted  You really doing great, In my opinion  you are an open source enthusiast, So Don't forget to checkout this open source  event  also, one of my friend is participating there 
Checkout the Link: ⬇️
https://devfest.ai/nocode-leaderboard/cm1auef9p000870ebzxkjhl73?claim=true

**Comment by RahulScripted** [comment]
> Hey 👋, @RahulScripted You really doing great, In my opinion you are an open source enthusiast, So Don't forget to checkout this open source event also, one of my friend is participating there Checkout the Link: ⬇️ https://devfest.ai/nocode-leaderboard/cm1auef9p000870ebzxkjhl73?claim=true

@Evgenii-Bazhaov Thank you🥰 I'll definitely check it out
