### ISSUE TITLE
Card Match Game

### ISSUE THREAD

**Issue by AkshitSalwan** [Evgenii-Bazhaov/Hacktoberfest2024#25]
It is a simple card match game where user needs to match two cards containing same emojis in a continuous trend to make it count ,at the end score is displayed.
<img width="494" alt="Screenshot 2024-10-14 at 2 45 27 PM" src="https://github.com/user-attachments/assets/e50e9612-8475-4c11-8f1e-02e91d96820a">

**Comment by Nityom** [comment]
Please assign it to me

**Comment by aryaman0406** [comment]
Hi @Evgenii-Bazhaov please assign this task to me.

**Comment by Evgenii-Bazhaov** [comment]
@AkshitSalwan  are you working right now?

**Comment by Evgenii-Bazhaov** [comment]
I am assigning to @Nityom , because he asked first.

**Comment by Evgenii-Bazhaov** [comment]
@Nityom Please complete it as early you can

**Comment by Nityom** [comment]
issue solved , output : 
![image](https://github.com/user-attachments/assets/1cc452dd-0e21-4777-8268-d92e30628c6d)
