### ISSUE TITLE
A Weather Application for getting weather details and to search weather details for other cities and countries.

### ISSUE THREAD

**Issue by 2021eo3ar** [Evgenii-Bazhaov/Hacktoberfest2024#26]
Here are the features of this app - 

1. Fetch weather of  current location
2. Next five days forecast
3. Forecast for another cities
4. weather details in depth

So please assign this issue to me with hacktoberFest lable.

**Comment by 2021eo3ar** [comment]
@Evgenii-Bazhaov I have raised the PR for weather application, kindly review and merge it

**Comment by Evgenii-Bazhaov** [comment]
you can now work on issue

**Comment by BaniSinghgithub** [comment]
hello sir @2021eo3ar , @Evgenii-Bazhaov  
I have prepared a weather app, pls review it.
If you want, I can create PR.

![image](https://github.com/user-attachments/assets/bcf45fdf-e367-44b4-ac49-61139c2601b2)

**Comment by 2021eo3ar** [comment]
I am not maintainer of this repo,you can raise a PR and @Evgenii-Bazhaov will merge it.

**Comment by BaniSinghgithub** [comment]
okk
thanks

**Comment by Evgenii-Bazhaov** [comment]
Hi👋, @everyone can you please up-vote for him in devfest ai challenge. Please click the link below and claim bonus to support. Thanks
➡️ https://devfest.ai/nocode-leaderboard/cm1auef9p000870ebzxkjhl73?claim=true
