### ISSUE TITLE
W3 schools web page clone 

### ISSUE THREAD

**Issue by Ashutosh7-kumar** [Evgenii-Bazhaov/Hacktoberfest2024#86]
please add under **hacktoberfest2024!** 
A popular educational platform known for its tutorials and references on web development technologies such as HTML, CSS, JavaScript, and more. This clone replicates the site's clean, user-friendly interface, providing easy access to coding examples, tutorials, and interactive learning features. By recreating the W3Schools layout.

**Comment by yuvi-mittal** [comment]
Can i get it assigned ?
