### ISSUE TITLE
Python Student Database Management System

### ISSUE THREAD

**Issue by AvgBlank** [Evgenii-Bazhaov/Hacktoberfest2024#92]
# Student Database Management System
The Student Database Management System is a comprehensive solution designed to efficiently manage student information using SQLite3. This project simplifies the task of storing, retrieving, and manipulating student records, offering a user-friendly interface for administrators or educators. Developed with SQLite3, Python, and various libraries, this system ensures reliability and ease of use in managing student data.

## Preview

https://github.com/AverageBlank/StudentDatabase/assets/112507212/40ec087f-5a14-4cc7-b8a1-2d08d2c91d59

### Prerequisites

Make sure you have Python installed on your system.

- **[Python](https://www.python.org/downloads/)**: Download and install Python.

### Installation Steps

1. **Clone the repository**

   ```bash
   git clone https://github.com/AverageBlank/StudentDatabase.git
   cd StudentDatabase
   ```

2. **Create a virtual environment (Optional)**

   ```bash
   python -m venv venv
   source venv/Scripts/activate  # On windows use `venv\bin\activate`
   ```

3. **Install the required libraries**

   ```bash
   pip install -r requirements.txt
   ```

4. **Run the application**
   ```bash
   python main.py
   ```

## Languages Used

- **Python**: The main programming language used for the backend.
- **SQL**: Language used for interacting with the SQLite3 database.

## Libraries Used

- **math**: Provides mathematical functions.
- **os**: Allows interaction with the operating system.
- **string**: Implements common string operations.
- **time**: Provides various time-related functions.
- **questionary**: A Python library for building interactive command-line applications.
- **matplotlib**: A plotting library for the Python programming language.
- **pandas**: A fast, powerful, and flexible open-source data analysis and manipulation library.
- **rich**: A Python library for rich text and beautiful formatting in the terminal.
- **sys**: Provides access to some variables used or maintained by the Python interpreter and to functions that interact strongly with the interpreter.
- **sqlite3**: A built-in Python library for interacting with SQLite databases.
- **cryptography (fernet)**: A cryptography library for secure communications. Fernet is used for encryption and decryption.

**Comment by AvgBlank** [comment]
Hey! I would like to add this program, could this be assigned to me?

**Comment by Evgenii-Bazhaov** [comment]
> Hey! I would like to add this program, could this be assigned to me?

Nice work✨
